//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public decimal PERS_CODIGO { get; set; }
        public string PERS_NOMBRE { get; set; }
        public string PERS_APELLIDO { get; set; }
        public string PERS_NRO_DOCUMENTO { get; set; }
        public string PERS_CORREO { get; set; }
        public string PERS_TELEFONO { get; set; }
        public Nullable<System.DateTime> PERS_FCH_NACIMIENTO { get; set; }
    }
}
